version: "3.5"

services:
  api-gateway:
    image: superj80820/api-gateway:latest
    restart: always
    volumes:
      - ./*.worldcrater.com:/api-gateway/*.worldcrater.com
      - ./messfar.com:/api-gateway/messfar.com
    ports:
      - 8090:3003
    networks:
      - intranet
    entrypoint: npm start

networks:
  intranet:
    name: intranet
