version: "3.5"

services:
  api-gateway:
    image: superj80820/api-gateway:latest
    restart: always
    ports:
      - 3003:3003
    networks:
      - intranet
    entrypoint: npm start

networks:
  intranet:
    name: intranet
