version: "3.5"

services:
  file-service:
    image: superj80820/file-service
    restart: always
    ports:
      - 3001:3001
    networks:
      - intranet
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env

networks:
  intranet:
    name: intranet