version: "3.5"

services:
  file-service:
    build: .
    restart: always
    ports:
      - 3001:3001
    networks:
      - intranet
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env
      - ./credentials:/.aws/credentials

networks:
  intranet:
    name: intranet