version: "3.5"

services:
  auth-service:
    image: superj80820/auth-service:latest
    restart: always
    volumes:
      - ./key.private.pem:/auth-service/cert/key.private.pem
      - ./key.public.pem:/auth-service/cert/key.public.pem
    ports:
      - 3005:3005
    networks:
      - intranet
    entrypoint: npm start
    env_file:
      - ./.env

networks:
  intranet:
    name: intranet
