version: "3.5"

services:
  auth-service:
    image: superj80820/auth-service:latest
    restart: always
    ports:
      - 3005:3005
    networks:
      - intranet
    entrypoint: npm start
    env_file:
      - ./.env

networks:
  intranet:
    name: intranet
