version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - intranet
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - intranet
    ports:
      - 8080:8080

networks:
  intranet:
    name: intranet
