apiVersion: batch/v1
kind: Job
metadata:
  name: face-parsing-job
spec:
  template:
    spec:
      containers:
      - name: face-parsing
        imagePullPolicy: Always
        image: superj80820/face-parsing
        env:
        - name: FACE_SERVICE
          valueFrom:
            configMapKeyRef:
              name: global-configmap
              key: service.face
        - name: UPLOAD_COUNT
          value: "0"
        - name: RESOURCE_URL_PAGE
          value: "1"
      restartPolicy: Never
  backoffLimit: 1