apiVersion: apps/v1
kind: Deployment
metadata:
  name: messfar-line-deployment
  labels:
    app: messfar-line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messfar-line
  template:
    metadata:
      labels:
        app: messfar-line
    spec:
      containers:
      - name: messfar-line
        imagePullPolicy: Always
        image: superj80820/messfar-line-service
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: redis.password
        - name: RECOGNITION_URL
          valueFrom:
            configMapKeyRef:
              name: global-configmap
              key: service.face
        - name: LINE_TOKEN
          value: "YT5evrjhdZNl8G5Zg4HwqB5+dvlPj5wu2xHr1m4V0R9t+b7POasYntkKKKFCqo5ACCQEQhigtS5PIKjBsuZ4qF9yrmLg5FodRHT9HfTD74w3w8vWK73Zsqp6N+tMhOHNjj56/KlSazD9B8Aj1gPVvwdB04t89/1O/w1cDnyilFU="
        - name: PORT
          value: "3002"
        command: ["npm", "start"]
        ports:
        - containerPort: 3002
