version: "3.5"

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    networks:
      - intranet
    volumes:
      - ./data:/data
    restart: always

networks:
  intranet:
    name: intranet
